### ISSUE TITLE
AndroidX也能用吗？不知道为什么集成之后APP打不开了

### ISSUE THREAD

**Issue by zaaach** [liys666666/DoubleClick#14]
```java
Caused by: java.lang.ClassNotFoundException: Didn't find class "net.zgyejy.yudongedu.base.YDApplication" on path: DexPathList[[zip file "/system/framework/org.apache.http.legacy.boot.jar", zip file "/data/app/net.zgyejy.yudongedu-0we0L7crKrJDNaQSxyOgew==/base.apk"],nativeLibraryDirectories=[/data/app/net.zgyejy.yudongedu-0we0L7crKrJDNaQSxyOgew==/lib/arm, /data/app/net.zgyejy.yudongedu-0we0L7crKrJDNaQSxyOgew==/base.apk!/lib/armeabi-v7a, /system/lib, /system/vendor/lib]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:134)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at android.app.AppComponentFactory.instantiateApplication(AppComponentFactory.java:50)
        at androidx.core.app.CoreComponentFactory.instantiateApplication(CoreComponentFactory.java:47)
        at android.app.Instrumentation.newApplication(Instrumentation.java:1120)
        at android.app.LoadedApk.makeApplication(LoadedApk.java:1061)
```

**Comment by liys666666** [comment]
暂时还没兼容AndroidX
